"""Foreign key updates

Revision ID: 0f833dac2556
Revises: 9fbaaf56d8a0
Create Date: 2022-06-07 15:55:39.504042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f833dac2556'
down_revision = '9fbaaf56d8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
