"""Foreign key updates

Revision ID: 17d9d6162298
Revises: fbfdc2bbf3bb
Create Date: 2022-06-04 23:50:46.044745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d9d6162298'
down_revision = 'fbfdc2bbf3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
