"""Foreign key updates

Revision ID: 1b3f5144dc07
Revises: 9aac65542da2
Create Date: 2022-06-07 16:11:17.786050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3f5144dc07'
down_revision = '9aac65542da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
