"""Foreign key updates

Revision ID: 3cb7a5d83c1e
Revises: fecb790aeafb
Create Date: 2022-06-04 21:26:05.880851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb7a5d83c1e'
down_revision = 'fecb790aeafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
