"""Foreign key updates

Revision ID: 416db1662ca5
Revises: d90db024f845
Create Date: 2022-06-04 20:36:10.778732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416db1662ca5'
down_revision = 'd90db024f845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
