"""Foreign key updates

Revision ID: 871c6a9ff952
Revises: 416db1662ca5
Create Date: 2022-06-04 20:38:47.509666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871c6a9ff952'
down_revision = '416db1662ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
