"""Foreign key updates

Revision ID: 9aac65542da2
Revises: ffdcac3e8af6
Create Date: 2022-06-07 15:58:19.632517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aac65542da2'
down_revision = 'ffdcac3e8af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
