"""Foreign key updates

Revision ID: 9fbaaf56d8a0
Revises: d66469919d10
Create Date: 2022-06-07 15:51:17.707106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbaaf56d8a0'
down_revision = 'd66469919d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
