"""Foreign key updates

Revision ID: a174d5f54b54
Revises: e07a3bd9d314
Create Date: 2022-06-04 21:39:31.051125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a174d5f54b54'
down_revision = 'e07a3bd9d314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
