"""Foreign key updates

Revision ID: d66469919d10
Revises: 17d9d6162298
Create Date: 2022-06-04 23:52:39.640828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66469919d10'
down_revision = '17d9d6162298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
