"""Comments and Seen added

Revision ID: d90db024f845
Revises: 073611a6bfc8
Create Date: 2022-06-02 15:29:48.571202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90db024f845'
down_revision = '073611a6bfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('feeds', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('publishers', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('publishers', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishers', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('publishers', 'description')
    op.alter_column('feeds', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('seen')
    op.drop_table('comments')
    # ### end Alembic commands ###
