"""Foreign key updates

Revision ID: ddb8a152470a
Revises: 1b3f5144dc07
Create Date: 2022-06-07 16:57:28.704619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb8a152470a'
down_revision = '1b3f5144dc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
