"""Foreign key updates

Revision ID: e07a3bd9d314
Revises: 3cb7a5d83c1e
Create Date: 2022-06-04 21:26:30.931895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07a3bd9d314'
down_revision = '3cb7a5d83c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
