"""Foreign key updates

Revision ID: fbfdc2bbf3bb
Revises: a174d5f54b54
Create Date: 2022-06-04 23:10:25.235449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfdc2bbf3bb'
down_revision = 'a174d5f54b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
