"""Foreign key updates

Revision ID: fecb790aeafb
Revises: 871c6a9ff952
Create Date: 2022-06-04 20:39:10.078452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecb790aeafb'
down_revision = '871c6a9ff952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
